In [24]:
import gym
import numpy
import numpy as np
import random

In [25]:
import os
import sys
import import_ipynb

os.chdir('/Users/jang-gihwan/Desktop/DeepLearing/ReinforcementLearning/_07_Olymic/ENV')
from wrapper import CompetitionOlympicsEnvWrapper
import running_args
os.chdir('/Users/jang-gihwan/Desktop/DeepLearing/ReinforcementLearning')
print("before: %s"%os.getcwd())
from termproject_olympic.env.chooseenv import make

before: /Users/jang-gihwan/Desktop/DeepLearing/ReinforcementLearning


In [26]:
def make_env(env_name, agent=None, config=None):
    env = make(env_type="olympics-integrated", game_name=env_name)
    env = CompetitionOlympicsEnvWrapper(env, args=config)
    return env

In [27]:
env = make_env(env_name = "olympics-running", config = running_args.get_args())

env_type = 'olympics-integrated'
!!olympics-running
game_name = 'olympics-running'


In [33]:
print("[olympic-running-observation_space]")
# agent 0's observation
print("[Agent 0's observation]")
env.reset()
print(env.get_all_observes()[0]["obs"]["agent_obs"][33])
print("[Agent 0's observation shape]")
print(env.get_all_observes()[0]["obs"]["agent_obs"].shape)
# agent 1's observation
print("[Agent 1's observation]")
print(env.get_all_observes()[1]["obs"]["agent_obs"])
print("[Agent 1's observation shape]")
print(env.get_all_observes()[1]["obs"]["agent_obs"].shape)

[olympic-running-observation_space]
[Agent 0's observation]
[ 0.  8.  8.  8.  8.  8.  8.  8.  8.  8.  0.  0.  0.  0.  0.  0. 10. 10. 10. 10. 10. 10. 10. 10. 10.  0.  0.  6.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[Agent 0's observation shape]
(40, 40)
[Agent 1's observation]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  6.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  6.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  6.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  6.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  6.  0.  0.  

In [6]:
print("[olympic-running-observation_variable_Info]")
print("Agent 0 : ", 10)
print("Agent 1 : ", 8)
print("Stadium : ", 6)
print("Arrows : ", 4)
print("Arrival line : ", 7)

[olympic-running-observation_variable_Info]
Agent 0 :  10
Agent 1 :  8
Stadium :  6
Arrows :  4
Arrival line :  7


In [7]:
print("[olympic-running-observation_Action_Info]")
print("Continuous Action Space")
print("Force : -100 ~ 200")
print("Angle : -30 ~ 30")

[olympic-running-observation_Action_Info]
Continuous Action Space
Force : -100 ~ 200
Angle : -30 ~ 30
