In [1]:
import gymnasium as gym; print(f"gym.__version__: {gym.__version__}")
import numpy as np

gym.__version__: 0.29.1


In [2]:
np.set_printoptions(edgeitems=10, linewidth=100000, formatter=dict(float=lambda x: "%7.3f" % x))

In [3]:
env = gym.make("LunarLander-v2", render_mode="human")

In [4]:
def observation_and_action_space_info():
    #####################
    # observation space #
    #####################
    print("*" * 80)
    print("[observation_space]")
    print("env.observation_space: ", env.observation_space)
    print("env.observation_space.high:", env.observation_space.high)
    print("env.observation_space.low:", env.observation_space.low)
    print("env.observation_space.shape:", env.observation_space.shape)
    for i in range(10):
        print(env.observation_space.sample())
    print()

    print("*" * 80)
    ################
    # action space #
    ################
    print("[action_space]")
    print(env.action_space)
    print("env.action_space.n:", env.action_space.n)
    print("env.action_space.shape:", env.action_space.shape)
    for i in range(10):
        print(env.action_space.sample(), end=" ")

In [5]:
if __name__ == "__main__":
    observation_and_action_space_info()

********************************************************************************
[observation_space]
env.observation_space:  Box([ -1.500  -1.500  -5.000  -5.000  -3.142  -5.000  -0.000  -0.000], [  1.500   1.500   5.000   5.000   3.142   5.000   1.000   1.000], (8,), float32)
env.observation_space.high: [  1.500   1.500   5.000   5.000   3.142   5.000   1.000   1.000]
env.observation_space.low: [ -1.500  -1.500  -5.000  -5.000  -3.142  -5.000  -0.000  -0.000]
env.observation_space.shape: (8,)
[  0.832   0.538  -0.843  -2.191  -0.179  -1.008   0.533   0.038]
[ -0.857   0.236   2.957  -0.782   0.915  -4.039   0.212   0.203]
[ -0.311  -0.343  -3.850   0.210  -2.732  -1.544   0.311   0.410]
[ -1.125   0.053  -2.981   3.616   0.472   3.458   0.190   0.108]
[  0.974  -0.803   4.718  -4.368  -1.177  -0.534   0.597   0.617]
[  0.796   0.858   3.893  -3.480   1.325  -0.440   0.441   0.899]
[  1.077  -0.104   2.712   2.952  -1.426   1.918   0.703   0.697]
[ -1.088   0.819  -3.277   1.514  -0.03