In [1]:
# https://gymnasium.farama.org/environments/classic_control/pendulum
import gymnasium as gym
import time
import numpy as np

In [2]:
print("gym.__version__:", gym.__version__)
np.set_printoptions(formatter={'float': '{:5.2f}'.format})

gym.__version__: 0.29.1


In [15]:
env = gym.make('Pendulum-v1', render_mode="human")

In [16]:
def env_info_details():
    print("*" * 80)
    print("[observation_space]")
    print(env.observation_space)
    print("shape : ",env.observation_space.shape)
    for i in range(10):
        print(env.observation_space.sample())
    print()

    print("*" * 80)
    print("[action_space]")
    print(env.action_space)
    print("shape : ",env.action_space.shape)
    for i in range(10):
        print(env.action_space.sample())
    print()

    print("*" * 80)
    observation, info = env.reset()

    action = env.action_space.sample()
    next_observation, reward, terminated, truncated, info = env.step(action)

    print("Obs.: {0}, Action: {1}, Next Obs.: {2}, Reward: {3:6.2f}, "
          "Terminated: {4}, Truncated: {5}, Info: {6}".format(
        observation, action, next_observation, reward, terminated, truncated, info
    ))

    observation = next_observation

    time.sleep(3)

    action = env.action_space.sample()
    next_observation, reward, terminated, truncated, info = env.step(action)

    print("Obs.: {0}, Action: {1}, Next Obs.: {2}, Reward: {3:6.2f}, "
          "Terminated: {4}, Truncated: {5}, Info: {6}".format(
        observation, action, next_observation, reward, terminated, truncated, info
    ))

    print("*" * 80)
    time.sleep(2)

In [17]:
if __name__ == "__main__":
    env_info_details()

********************************************************************************
[observation_space]
Box([-1.00 -1.00 -8.00], [ 1.00  1.00  8.00], (3,), float32)
shape :  (3,)
[-0.77  0.39  0.51]
[ 0.07 -0.62  4.15]
[-0.74 -0.38  1.99]
[-0.99 -0.09 -1.51]
[-0.42 -0.23 -1.97]
[ 0.64 -0.75 -3.85]
[ 0.30  0.58  3.60]
[-0.16  0.83 -2.65]
[ 0.84  0.04 -7.26]
[-0.79  0.32 -4.72]

********************************************************************************
[action_space]
Box(-2.0, 2.0, (1,), float32)
shape :  (1,)
[-0.02]
[ 0.33]
[-0.72]
[-0.70]
[ 0.43]
[ 1.71]
[-1.73]
[ 1.11]
[ 0.91]
[-0.71]

********************************************************************************
Obs.: [-0.93 -0.36  0.21], Action: [-1.46], Next Obs.: [-0.94 -0.35 -0.28], Reward:  -7.69, Terminated: False, Truncated: False, Info: {}
Obs.: [-0.94 -0.35 -0.28], Action: [ 1.42], Next Obs.: [-0.94 -0.33 -0.33], Reward:  -7.77, Terminated: False, Truncated: False, Info: {}
*********************************************

- observation shape : 3
- action shape : 1